version: '3.8'

services:
  app:
    build:
      context: ./aws-test-app
    container_name: next-app
    restart: unless-stopped
    expose:
      - "3000"  # internal port for NGINX to connect to
    networks:
      - webnet

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"  # public port
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - webnet

networks:
  webnet:
