- name: Debug HOST secret
  env:
    HOST: ${{ secrets.HOST }}
  run: |
    echo "HOST is: '$HOST'"
    if [ -z "$HOST" ]; then
      echo "ERROR: HOST secret is missing or empty!"
      exit 1
    fi
