name: Test Secrets Access

on:
  push:
    branches:
      - main

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    # environment: production  # temporarily disabled

    steps:
      - name: Print secrets
        env:
          DEPLOYKEY: ${{ secrets.DEPLOYKEY }}
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USER }}
        run: |
          echo "DEPLOYKEY length: ${#DEPLOYKEY}"
          echo "HOST: '$HOST'"
          echo "USER: '$USER'"
          if [ -z "$DEPLOYKEY" ] || [ -z "$HOST" ] || [ -z "$USER" ]; then
            echo "One or more secrets are empty!"
            exit 1
          fi
